#!/bin/bash
#
# BEN - Build Everything Now
# Copyright (C) 2023  M E Leypold
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# $1 - path to be split
# $2 - worktree (checked out) into which to merge)

if test "$#" -ne 3; then
    echo >&2 "Need exactly two arguments: SPLIT_DIR, WORKTREE (path) and MESSAGE"
    exit 1
fi

set -eu
set -o pipefail

SPLIT_DIR="$1"
WORKTREE="$2"
MESSAGE="$3"

COMMIT="$(git subtree split -P "$SPLIT_DIR")"
echo "Commit $COMMIT split out, will be merged"

cd "$WORKTREE"
git merge -m "$MESSAGE" "$COMMIT"

